### ISSUE TITLE
Endless loop 

### ISSUE THREAD

**Issue by GoceBogdanovski** [shhdharmen/mat-menu-dynamic-data#1]
You have endless loop in MenuComponent class in this function:
isExpandable(node: string) {
    console.log('isExpandable', node);
    return this.database.isExpandable(node);
  }

**Comment by shhdharmen** [comment]
Can you create a stackblitz to show the issue?

**Comment by GoceBogdanovski** [comment]
here it is. open the sub menus and there it is :)

https://stackblitz.com/edit/shhdharmen-mat-menu-dynamic-data-cjjnssfv?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fmenu%2Fmenu.component.ts,src%2Fapp%2Fmenu%2Fmenu.component.html,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fdynamic-database.service.ts

![image](https://github.com/user-attachments/assets/f3aa2669-06ac-4763-9d0f-78e181e02346)

**Comment by shhdharmen** [comment]
It's not infinite loop. You are seeing lots of logs because we are calling a function in template. `isExpandable` is a pure function, so there should not be any performance impact using that function in template. If you don't want to use function in template, you can also try to create a pure pipe instead.

**Comment by GoceBogdanovski** [comment]
i agree, it is finite.
i am sorry for my bad explanation.

my proposal here is to create different data structure, something like:
`interface MenuModel {
name: string,
children: MenuModel[]
}`
and pass the children as data source for the next loop in the recursion, 
in order to skip those 2000 checks for 5 menu items.

**Comment by GoceBogdanovski** [comment]
StackBlitz example from my proposal
https://stackblitz.com/edit/angular-material-menu-with-dynamic-data
